### ISSUE TITLE
请问有计划支持中央新风的控制吗？

### ISSUE THREAD

**Issue by kamingchan** [mypal/ha-dsair#26]

**Comment by lynn901** [comment]
同样想问，啥时候支持新风

**Comment by lynn901** [comment]
> 没有这个设备，没办法调试。等我下次装修搞到新风设备的时候吧😂

我现在手头上有个环境可以debug

**Comment by ItownTech** [comment]
同问

**Comment by ypwub5** [comment]
@lynn901  @ItownTech 

尝试加入了新风的控制，目前只实现了开关控制，热交换和风量调节还在研究。
可以在我的 [fork](https://github.com/ypwub5/ha-dsair/tree/vent) 里面下载代码测试

------

我的新风机型是 vam250gmve，控制器是 D611，看反编译的安卓代码好像只能支持开关控制。
但是在 iOS 版里又能看到热交换和风量的选项，不过好像也只是个按钮，点击后新风的面板并不会改变状态。
所以风量以及热交换状态一类的还在研究，不知道你们的新风在 金制空气 里面能不能控制风量热交换一类的。 

另外，你们试过最新改版的 金制空气app 和 D611 的新固件了吗？

**Comment by kamingchan** [comment]
iOS版本的金制空气（包括新版、旧版）一直可以控制风量、热交换。

**Comment by ypwub5** [comment]
> iOS版本的金制空气（包括新版、旧版）一直可以控制风量、热交换。

难道是我的新风机型号比较旧，不兼容么... 我更新固件和app再试一下
多谢反馈

**Comment by lynn901** [comment]
> @lynn901 @ItownTech
> 
> 尝试加入了新风的控制，目前只实现了开关控制，热交换和风量调节还在研究。 可以在我的 [fork](https://github.com/ypwub5/ha-dsair/tree/vent) 里面下载代码测试
> 
> 我的新风机型是 vam250gmve，控制器是 D611，看反编译的安卓代码好像只能支持开关控制。 但是在 iOS 版里又能看到热交换和风量的选项，不过好像也只是个按钮，点击后新风的面板并不会改变状态。 所以风量以及热交换状态一类的还在研究，不知道你们的新风在 金制空气 里面能不能控制风量热交换一类的。
> 
> 另外，你们试过最新改版的 金制空气app 和 D611 的新固件了吗？

我使用最新的app和固件，现在的这个插件都不支持了，获取不到网关的信息了~

**Comment by lynn901** [comment]
> @lynn901 @ItownTech
> 
> 尝试加入了新风的控制，目前只实现了开关控制，热交换和风量调节还在研究。 可以在我的 [fork](https://github.com/ypwub5/ha-dsair/tree/vent) 里面下载代码测试
> 
> 我的新风机型是 vam250gmve，控制器是 D611，看反编译的安卓代码好像只能支持开关控制。 但是在 iOS 版里又能看到热交换和风量的选项，不过好像也只是个按钮，点击后新风的面板并不会改变状态。 所以风量以及热交换状态一类的还在研究，不知道你们的新风在 金制空气 里面能不能控制风量热交换一类的。
> 
> 另外，你们试过最新改版的 金制空气app 和 D611 的新固件了吗？

最好提个pr，别分化版本了~

**Comment by kamingchan** [comment]
```
2022-08-19 22:40:39.809 ERROR (Thread-5) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/config/custom_components/ds_air/ds_air_service/service.py", line 134, in run
    Service.poll_status()
  File "/config/custom_components/ds_air/ds_air_service/service.py", line 342, in poll_status
    for v in Service._ventilations:
TypeError: 'NoneType' object is not iterable
```

**Comment by ItownTech** [comment]
> > @lynn901 @ItownTech
> > 尝试加入了新风的控制，目前只实现了开关控制，热交换和风量调节还在研究。 可以在我的 [fork](https://github.com/ypwub5/ha-dsair/tree/vent) 里面下载代码测试
> > 我的新风机型是 vam250gmve，控制器是 D611，看反编译的安卓代码好像只能支持开关控制。 但是在 iOS 版里又能看到热交换和风量的选项，不过好像也只是个按钮，点击后新风的面板并不会改变状态。 所以风量以及热交换状态一类的还在研究，不知道你们的新风在 金制空气 里面能不能控制风量热交换一类的。
> > 另外，你们试过最新改版的 金制空气app 和 D611 的新固件了吗？
> 
> 我使用最新的app和固件，现在的这个插件都不支持了，获取不到网关的信息了~



> > @lynn901 @ItownTech
> > 尝试加入了新风的控制，目前只实现了开关控制，热交换和风量调节还在研究。 可以在我的 [fork](https://github.com/ypwub5/ha-dsair/tree/vent) 里面下载代码测试
> > 我的新风机型是 vam250gmve，控制器是 D611，看反编译的安卓代码好像只能支持开关控制。 但是在 iOS 版里又能看到热交换和风量的选项，不过好像也只是个按钮，点击后新风的面板并不会改变状态。 所以风量以及热交换状态一类的还在研究，不知道你们的新风在 金制空气 里面能不能控制风量热交换一类的。
> > 另外，你们试过最新改版的 金制空气app 和 D611 的新固件了吗？
> 
> 我使用最新的app和固件，现在的这个插件都不支持了，获取不到网关的信息了~

我是最新的app和固件，这个插件支持的挺好的

**Comment by lynn901** [comment]
@ItownTech 我重新配了，空调和传感器是可以正常使用的，但是使用 @ypwub5 提供的插件，无法正常启动~

**Comment by ypwub5** [comment]
@lynn901  hello 前一阵折腾了些其他事...  最近研究了下可能是大金有两种新风系统类型导致的，我只做了 app 里定义为 ventilation 的类型， 没有处理 SmallVAM 这类新风。 

有时间可以帮忙测试一下这个 [branch](https://github.com/ypwub5/ha-dsair/tree/smallVAM) 吗，启动后看下 log 里面有没有一条类似 small vam found 的 waring。

**Comment by lynn901** [comment]
> 

@ypwub5 好的，我十一期间debug一下，方便的话加一下微信~

**Comment by zfgjy2005** [comment]
> @lynn901 hello 前一阵折腾了些其他事... 最近研究了下可能是大金有两种新风系统类型导致的，我只做了 app 里定义为 ventilation 的类型， 没有处理 SmallVAM 这类新风。
> 
> 有时间可以帮忙测试一下这个 [branch](https://github.com/ypwub5/ha-dsair/tree/smallVAM) 吗，启动后看下 log 里面有没有一条类似 small vam found 的 waring。

你好，原代码更新了，你这里可以把新风也更新下嘛

**Comment by ypwub5** [comment]
@zfgjy2005  hello/ [vent](https://github.com/ypwub5/ha-dsair/tree/vent) 分支同步了一下这边的 test ，我这里测试 D611 最新固件可以使用，但依然是只支持开关控制，因为最新固件依然不能切换我家新风机的旁通和热交换，没法测试，也就没做对应的功能

然后我打开了我 fork 的 issue 功能，新风问题去那边讨论吧，等差不多完善了我再看看能不能 merge 到这边

**Comment by zfgjy2005** [comment]
收到，谢谢@ypwub5

**Comment by fevenor** [comment]
> > 
> 
> @ypwub5 好的，我十一期间debug一下，方便的话加一下微信~

debug成功了吗，我也遇到取不到ventilations的问题

**Comment by lynn901** [comment]
> > > 
> > 
> > 
> > @ypwub5 好的，我十一期间debug一下，方便的话加一下微信~
> 
> debug成功了吗，我也遇到取不到ventilations的问题
没有成功，依旧是无法正常启动，没法debug

**Comment by lynn901** [comment]
> @lynn901 hello 前一阵折腾了些其他事... 最近研究了下可能是大金有两种新风系统类型导致的，我只做了 app 里定义为 ventilation 的类型， 没有处理 SmallVAM 这类新风。
> 
> 有时间可以帮忙测试一下这个 [branch](https://github.com/ypwub5/ha-dsair/tree/smallVAM) 吗，启动后看下 log 里面有没有一条类似 small vam found 的 waring。

@ypwub5 可以加你一下微信吗？最新有时间可以折腾一下这个

**Comment by lightrabbit** [comment]
@ypwub5 我最近也在测试新风的功能，我的设备是SmallVAM的。
然后我发现在我这里GetRoomInfo会拿不到新风的信息，但是用 `CAPABILITY_QUERY` 直接带上 `room_id` 和 `unit_id` 去查询就能拿到信息。
然后SmallVAM和VAM的 subbody 的定义会有些不同，可能需要单独的协议来处理，这个我也还在整。

**Comment by lightrabbit** [comment]
@lynn901 @ypwub5 我目前调通了自己这的设备，目前可以做到 开关、调整风速、修改模式 这三个功能。
代码在这个 [branch](https://github.com/lightrabbit/ha-dsair/tree/smallVAM) 上。我这目前启动后是能看到新风设备的。

然后我看SmallVAM的协议里面还能看到新风的进风口的PM2.5和温湿度信息，后续看看能不能把它作为传感器实体加到HA里。

**Comment by lynn901** [comment]
> @lynn901 @ypwub5 我目前调通了自己这的设备，目前可以做到 开关、调整风速、修改模式 这三个功能。 代码在这个 [branch](https://github.com/lightrabbit/ha-dsair/tree/smallVAM) 上。我这目前启动后是能看到新风设备的。
> 
> 然后我看SmallVAM的协议里面还能看到新风的进风口的PM2.5和温湿度信息，后续看看能不能把它作为传感器实体加到HA里。

我可以正常加载插件并且可以正常获取到传感器和空调设备，但是没有获取到新风设备，需要独立配置什么吗?

**Comment by lightrabbit** [comment]
> 我可以正常加载插件并且可以正常获取到传感器和空调设备，但是没有获取到新风设备，需要独立配置什么吗?

@lynn901 你看看能不能看到本地的代码，就是 `custom_component/ds_air/` 底下的内容，看一下里面有没有 `fan.py`。
如果没有的话，可能是你用 HACS 安装的时候，它默认用了 `test` 分支，而不是我链接里的 `smallVAM` 分支。
我现在把我这个仓库的默认分支改成了 `smallVAM`。你可以删掉之前的，重新安装一下再试试看。

理论上来说不需要额外配置什么，就只要确保 `网关型号` 那里选的是 `DTA117C611`，就可以了。

**Comment by lynn901** [comment]
> > 我可以正常加载插件并且可以正常获取到传感器和空调设备，但是没有获取到新风设备，需要独立配置什么吗?
> 
> @lynn901 你看看能不能看到本地的代码，就是 `custom_component/ds_air/` 底下的内容，看一下里面有没有 `fan.py`。 如果没有的话，可能是你用 HACS 安装的时候，它默认用了 `test` 分支，而不是我链接里的 `smallVAM` 分支。 我现在把我这个仓库的默认分支改成了 `smallVAM`。你可以删掉之前的，重新安装一下再试试看。
> 
> 理论上来说不需要额外配置什么，就只要确保 `网关型号` 那里选的是 `DTA117C611`，就可以了。
我的网关型号是DTA117B611,产生如下报错

2023-10-21 07:53:13.054 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] recv hex: 0x0258000d0001000f0000000819000000005900010121440300246f28c9cee00fe7a9bae6b094e4bca0e6849fe599a87f00db0000020b00a5020103000000011801ff7fff7fff7f4b000000e8030000023c000a000101011600080003
2023-10-21 07:53:13.054 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] ^[[31mrecv:^[[0m
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] ^[[31mSensor2InfoResult:^[[0m {
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] cmd_id: 15
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] cmd_type: SENSOR2_INFO
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] count: 1
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] mode: 1
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] need_ack: 1
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] room_id: 33
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] sensor_type: 3
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] sensors: [
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]     0: ^[[31mSensor:^[[0m {
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         alias: 空气传感器
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         co2: 677
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         co2_lower: 0
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         co2_upper: 1000
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         connected: True
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         hcho: 0
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         hcho_upper: 10
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         humidity: 512
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         humidity_lower: 32767
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         humidity_upper: 32767
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         id: 0
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         mac: 246f28c9cee0
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         name: 空气传感器
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         pm25: 11
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         pm25_lower: 0
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         pm25_upper: 75
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         room_id: 33
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         sensor_type: 3
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         sleep_mode_count: 1
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         start_time: 0
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         stop_time: 0
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         switch_on_off: True
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         temp: 219
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         temp_lower: 32767
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         temp_upper: 280
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         time_millis: 1697845993.0546288
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         tvoc: 3
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         tvoc_upper: 60
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         type1: 127
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         type2: 0
2023-10-21 07:53:13.058 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         unique_id: daikin_33_0
                                           2023-10-21 07:53:13.054 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] recv hex: 0x0258000d0001000f0000000819000000005900010121440300246f28c9cee00fe7a9bae6b094e4bca0e6849fe599a87f00db0000020b00a5020103000000011801ff7fff7fff7f4b000000e8030000023c000a000101011600080003
2023-10-21 07:53:13.054 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] ^[[31mrecv:^[[0m
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] ^[[31mSensor2InfoResult:^[[0m {
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] cmd_id: 15
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] cmd_type: SENSOR2_INFO
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] count: 1
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] mode: 1
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] need_ack: 1
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] room_id: 33
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] sensor_type: 3
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] sensors: [
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]     0: ^[[31mSensor:^[[0m {
2023-10-21 07:53:13.055 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         alias: 空气传感器
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         co2: 677
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         co2_lower: 0
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         co2_upper: 1000
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         connected: True
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         hcho: 0
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         hcho_upper: 10
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         humidity: 512
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         humidity_lower: 32767
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         humidity_upper: 32767
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         id: 0
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         mac: 246f28c9cee0
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         name: 空气传感器
2023-10-21 07:53:13.056 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         pm25: 11
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         pm25_lower: 0
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         pm25_upper: 75
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         room_id: 33
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         sensor_type: 3
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         sleep_mode_count: 1
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         start_time: 0
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         stop_time: 0
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         switch_on_off: True
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         temp: 219
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         temp_lower: 32767
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         temp_upper: 280
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         time_millis: 1697845993.0546288
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         tvoc: 3
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         tvoc_upper: 60
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         type1: 127
2023-10-21 07:53:13.057 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         type2: 0
2023-10-21 07:53:13.058 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         unique_id: daikin_33_0
2023-10-21 07:53:13.058 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         unit_id: 0
2023-10-21 07:53:13.058 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         voc: STEP_1
2023-10-21 07:53:13.058 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service]         voc_lower: 2}]
2023-10-21 07:53:13.058 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] subbody_ver: 1
2023-10-21 07:53:13.058 DEBUG (Thread-6) [custom_components.ds_air.ds_air_service.service] target: SENSOR}
2023-10-21 07:53:43.010 DEBUG (Thread-7) [custom_components.ds_air.ds_air_service.service] send hex: 0x02000003
2023-10-21 07:53:43.010 DEBUG (Thread-7) [custom_components.ds_air.ds_air_service.service] ^[[31msend:^[[0m
2023-10-21 07:53:43.010 DEBUG (Thread-7) [custom_components.ds_air.ds_air_service.service] ^[[31mHeartbeatParam:^[[0m {
2023-10-21 07:53:43.010 DEBUG (Thread-7) [custom_components.ds_air.ds_air_service.service] cmd_id: 16
2023-10-21 07:53:43.010 DEBUG (Thread-7) [custom_components.ds_air.ds_air_service.service] cmd_type: SYS_ACK
2023-10-21 07:53:43.010 DEBUG (Thread-7) [custom_components.ds_air.ds_air_service.service] cnt: 16
2023-10-21 07:53:43.011 DEBUG (Thread-7) [custom_components.ds_air.ds_air_service.service] has_result: False
2023-10-21 07:53:43.011 DEBUG (Thread-7) [custom_components.ds_air.ds_air_service.service] need_ack: 1
2023-10-21 07:53:43.011 DEBUG (Thread-7) [custom_components.ds_air.ds_air_service.service] subbody_ver: 1
2023-10-21 07:53:43.011 DEBUG (Thread-7) [custom_components.ds_air.ds_air_service.service] target: SYSTEM}
2023-10-21 07:53:50.029 DEBUG (Thread-5) [custom_components.ds_air.ds_air_service.service] send hex: 0x02000003
2023-10-21 07:53:50.030 DEBUG (Thread-5) [custom_components.ds_air.ds_air_service.service] ^[[31msend:^[[0m
2023-10-21 07:53:50.030 DEBUG (Thread-5) [custom_components.ds_air.ds_air_service.service] ^[[31mHeartbeatParam:^[[0m {
2023-10-21 07:53:50.030 DEBUG (Thread-5) [custom_components.ds_air.ds_air_service.service] cmd_id: 17
2023-10-21 07:53:50.030 DEBUG (Thread-5) [custom_components.ds_air.ds_air_service.service] cmd_type: SYS_ACK
2023-10-21 07:53:50.030 DEBUG (Thread-5) [custom_components.ds_air.ds_air_service.service] cnt: 17
2023-10-21 07:53:50.030 DEBUG (Thread-5) [custom_components.ds_air.ds_air_service.service] has_result: False
2023-10-21 07:53:50.031 DEBUG (Thread-5) [custom_components.ds_air.ds_air_service.service] need_ack: 1
2023-10-21 07:53:50.031 DEBUG (Thread-5) [custom_components.ds_air.ds_air_service.service] subbody_ver: 1
2023-10-21 07:53:50.031 DEBUG (Thread-5) [custom_components.ds_air.ds_air_service.service] target: SYSTEM}
2023-10-21 07:54:09.182 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 金制空气 for ds_air
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ds_air/__init__.py", line 49, in async_setup_entry
    await hass.async_add_executor_job(Service.init, host, port, scan_interval)
asyncio.exceptions.CancelledError: aiohttp connection lost
2023-10-21 07:54:43.012 DEBUG (Thread-7) [custom_components.ds_air.ds_air_service.service] send hex: 0x02000003
2023-10-21 07:54:43.012 DEBUG (Thread-7) [custom_components.ds_air.ds_air_service.service] ^[[31msend:^[[0m
2023-10-21 07:54:43.012 DEBUG (Thread-7) [custom_components.ds_air.ds_air_service.service] ^[[31mHeartbeatParam:^[[0m {
2023-10-21 07:54:43.012 DEBUG (Thread-7) [custom_components.ds_air.ds_air_service.service] cmd_id: 18
2023-10-21 07:54:43.012 DEBUG (Thread-7) [custom_components.ds_air.ds_air_service.service] cmd_type: SYS_ACK
2023-10-21 07:54:43.012 DEBUG (Thread-7) [custom_components.ds_air.ds_air_service.service] cnt: 18
2023-10-21 07:54:43.012 DEBUG (Thread-7) [custom_components.ds_air.ds_air_service.service] has_result: False
2023-10-21 07:54:43.012 DEBUG (Thread-7) [custom_components.ds_air.ds_air_service.service] need_ack: 1

**Comment by lynn901** [comment]
@lightrabbit 看日志是没有正常获取到room id

**Comment by lightrabbit** [comment]
> @lightrabbit 看日志是没有正常获取到room id，看你之前的评论是改了请求名称SYS_GET_ROOM_INFO_V1，从我的日志看，用的就是这个方法，感觉需要给改回来

这样看B611和D611的差别还挺大的，你看方便加我微信号吗？有时间的时候可以一起调试一下，微信号和我github号相同。

**Comment by lynn901** [comment]
> > @lightrabbit 看日志是没有正常获取到room id，看你之前的评论是改了请求名称SYS_GET_ROOM_INFO_V1，从我的日志看，用的就是这个方法，感觉需要给改回来
> 
> 这样看B611和D611的差别还挺大的，你看方便加我微信号吗？有时间的时候可以一起调试一下，微信号和我github号相同。

```python
def do(self):
        if Config.is_new_version and Config.is_c611:
            p = GetRoomInfoParam(EnumCmdType.SYS_GET_ROOM_INFO_V1)
        else:
            p = GetRoomInfoParam(EnumCmdType.SYS_GET_ROOM_INFO)
        p.room_ids.append(0xffff)
``` 
加了些判断，现在可以了

**Comment by devkaiwang** [comment]
请问新风支持可以用了吗？

**Comment by mypal** [comment]
> 请问新风支持可以用了吗？

@lynn901 的fork版本似乎支持，可以试试看。如果功能比较稳定，可以合入过来，我发个包。

**Comment by misaka4e21** [comment]
> > 请问新风支持可以用了吗？
> 
> [@lynn901](https://github.com/lynn901) 的fork版本似乎支持，可以试试看。如果功能比较稳定，可以合入过来，我发个包。

我之前用过一段时间 @lightrabbit 的 fork 版本，后来更新版本发现不能用了，于是简单修了下几个调用，目前在 Core 2025.1.4能够正常加载运行。各位前辈可以帮忙测试一下，谢谢。

**Comment by llcc01** [comment]
根据上面的fork，修改了一下，适配了标准新风的电源开关、风量控制和模式选择，测试过可用
[https://github.com/llcc01/ha-dsair](https://github.com/llcc01/ha-dsair)

我这里的版本是 Core 2025.1.1

**Comment by lightrabbit** [comment]
> > > 请问新风支持可以用了吗？
> > 
> > 
> > [@lynn901](https://github.com/lynn901) 的fork版本似乎支持，可以试试看。如果功能比较稳定，可以合入过来，我发个包。
> 
> 我之前用过一段时间 [@lightrabbit](https://github.com/lightrabbit) 的 fork 版本，后来更新版本发现不能用了，于是简单修了下几个调用，目前在 Core 2025.1.4能够正常加载运行。各位前辈可以帮忙测试一下，谢谢。

感谢测试，我这段时间比较忙，暂时没有精力修改代码，就在你的PR上面补充了下我之前和 @lynn901 测试后的结论，现在可能就差一个C611的测试结果了。

**Comment by kamingchan** [comment]
我是C611，用了一下misaka4e21的版本，似乎integration无法完成初始化。后续在 #87 讨论吧
