### ISSUE TITLE
重启后无法再次启用插件

### ISSUE THREAD

**Issue by sephrioth** [mypal/ha-dsair#36]
刚升级HA到2022.11，重启过程中ds-air失败，然后重启失败； 尝试过降级版本重启也一样会失败
重启过程中的报错日志如下：

`Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 218, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 225, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 243, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1625, in async_create_flow
    return HANDLERS[entry.domain].async_get_options_flow(entry)
  File "/config/custom_components/ds_air/config_flow.py", line 81, in async_get_options_flow
    return DsAirOptionsFlowHandler(config_entry)
  File "/config/custom_components/ds_air/config_flow.py", line 93, in __init__
    self._climates = list(map(lambda state: state.alias, Service.get_aircons()))
  File "/config/custom_components/ds_air/ds_air_service/service.py", line 204, in get_aircons
    return Service._new_aircons+Service._aircons+Service._bathrooms
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'`

然后尝试在重启过程中删除插件， 然后顺利重启进入系统， 重新添加插件， 安装成功后输入网关信息后就一直在初始化转圈圈， 然后就死在这里了...日志如下

`Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/config/custom_components/ds_air/ds_air_service/service.py", line 134, in run
    Service.poll_status()
  File "/config/custom_components/ds_air/ds_air_service/service.py", line 292, in poll_status
    for i in Service._new_aircons:
TypeError: 'NoneType' object is not iterable`

**Comment by sephrioth** [comment]
@mypal @xrh0905 大佬们能否帮忙看下，现在完全用不了了... 感谢!

**Comment by yuhuanfan** [comment]
我也遇到同样问题

**Comment by sephrioth** [comment]
> 我也遇到同样问题

你也是突然出现的么？ 我现在换啥HA版本都用不了这个插件了.... 好奇怪

**Comment by yuhuanfan** [comment]
> > 我也遇到同样问题
> 
> 你也是突然出现的么？ 我现在换啥HA版本都用不了这个插件了.... 好奇怪

我也是突然这样的不知道啥原因我的是DTA117D611wifi的你的是啥型号

**Comment by sephrioth** [comment]
> DTA117D611wifi

DTA117C611 有线版本

**Comment by yuhuanfan** [comment]
> > DTA117D611wifi
> 
> DTA117C611 有线版本

等老板更新吧!感觉老板好像也不管这个集成了!!!

**Comment by xrh0905** [comment]
网关固件版本多少? @yuhuanfan @sephrioth

**Comment by sephrioth** [comment]
> 网关固件版本多少? @yuhuanfan @sephrioth
> 我这里是好的...

02.10.00

**Comment by big111boy** [comment]
网关固件版本02.10.00，HA和OS版本未升级，重启后插件无法加载

**Comment by yuhuanfan** [comment]
> 网关固件版本多少? @yuhuanfan @sephrioth 我这里是好的...

03.03.00

**Comment by asukahan** [comment]
> > 网关固件版本多少? @yuhuanfan @sephrioth 我这里是好的...
> 
> 03.03.00

我的DTA117D611网关本来能用，前些天大金的app提示我网关更新固件我没理他，就怕更完了不行，结果今天DS-air全不能用了，打开app发现固件自己更新了……我的现在也是03.03.00

**Comment by sephrioth** [comment]
App 里面显示  02.10.00 已经就是最新版本固件了( DTA117C611)

**Comment by ItownTech** [comment]
我固件是03.03.00，也是报这样的错，wifi网关611

**Comment by ruleechen** [comment]
+1
网关固件版本 02.10.00 （显示当前为最新版本）
Home Assistant 2022.11.2
Supervisor 2022.10.2
Frontend 20221108.0 - latest

**Comment by bytebility** [comment]
DS-AIR 插件一直显示 “正在初始化” ，重启网关和HA都不行。

网关固件版本 02.10.00 （显示当前为最新版本）。
应该是网关的接口发生了变化。。。

**Comment by sephrioth** [comment]
今天大金的人和我说， 现在这个网关支持天猫精灵和华为语音助手控制了... 可能就是这次更新？

**Comment by TempleZhou** [comment]
+1

**Comment by ItownTech** [comment]
> 今天大金的人和我说， 现在这个网关支持天猫精灵和华为语音助手控制了... 可能就是这次更新？

和网关更新没关系，我9月份的时候就更新了，一直用的好好的，前两天重新装了HA，然后就报这个错了，降版本也不行

**Comment by ruleechen** [comment]
> > 今天大金的人和我说， 现在这个网关支持天猫精灵和华为语音助手控制了... 可能就是这次更新？
> 
> 和网关更新没关系，我9月份的时候就更新了，一直用的好好的，前两天重新装了HA，然后就报这个错了，降版本也不行

感觉是的，我也是更新了HA就直接不能用了，网关更新不会那么巧在同一个时间吧

**Comment by sephrioth** [comment]
> > 今天大金的人和我说， 现在这个网关支持天猫精灵和华为语音助手控制了... 可能就是这次更新？
> 
> 和网关更新没关系，我9月份的时候就更新了，一直用的好好的，前两天重新装了HA，然后就报这个错了，降版本也不行

HA这边没有任何变化， 大部分人只是重启就开始报错了， 我也尝试过降版本， 但是还是出错， 那错误如果不在HA的话， 只能在网关这边了...

**Comment by sephrioth** [comment]
> > > 今天大金的人和我说， 现在这个网关支持天猫精灵和华为语音助手控制了... 可能就是这次更新？
> > 
> > 
> > 和网关更新没关系，我9月份的时候就更新了，一直用的好好的，前两天重新装了HA，然后就报这个错了，降版本也不行
> 
> 感觉是的，我也是更新了HA就直接不能用了，网关更新不会那么巧在同一个时间吧

和更新HA没关系，你看前面的回复， 很多人重启后就挂了， 只是因为更新HA是需要重启的， 所以才建立了这种联系吧。

**Comment by big111boy** [comment]
> > > > 今天大金的人和我说， 现在这个网关支持天猫精灵和华为语音助手控制了... 可能就是这次更新？
> > > 
> > > 
> > > 和网关更新没关系，我9月份的时候就更新了，一直用的好好的，前两天重新装了HA，然后就报这个错了，降版本也不行
> > 
> > 
> > 感觉是的，我也是更新了HA就直接不能用了，网关更新不会那么巧在同一个时间吧
> 
> 和更新HA没关系，你看前面的回复， 很多人重启后就挂了， 只是因为更新HA是需要重启的， 所以才建立了这种联系吧。

正解，我从6月开始就没有升级过HA版本了，到11月初都正常使用，直到最近一次重启以后报错。

**Comment by ShaneGa0** [comment]
目前有大佬能解决吗

**Comment by sephrioth** [comment]
> 目前有大佬能解决吗
暂时还没有, 也找不到作者的联系方式....

**Comment by yuhuanfan** [comment]
> > 目前有大佬能解决吗
> 
> 暂时还没有, 也找不到作者的联系方式....

前几天通过qq问过作者了,说这个周末看看修改一下程序!!坐等了

**Comment by mypal** [comment]
#39 已修复，可以拉取下1.3.2版本
