### ISSUE TITLE
Mypal先生我的ha dsair不能用了

### ISSUE THREAD

**Issue by yuhuanfan** [mypal/ha-dsair#37]
Logger: aiohttp.server
Source: custom_components/ds_air/ds_air_service/service.py:204
Integration: DS-AIR (documentation)
First occurred: 15:02:15 (13 occurrences)
Last logged: 19:00:42

`此错误来自自定义集成。

Logger: aiohttp.server
Source: custom_components/ds_air/ds_air_service/service.py:204
Integration: DS-AIR (documentation)
First occurred: 15:02:15 (13 occurrences)
Last logged: 19:00:42

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 218, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 225, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 243, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1625, in async_create_flow
    return HANDLERS[entry.domain].async_get_options_flow(entry)
  File "/config/custom_components/ds_air/config_flow.py", line 81, in async_get_options_flow
    return DsAirOptionsFlowHandler(config_entry)
  File "/config/custom_components/ds_air/config_flow.py", line 93, in __init__
    self._climates = list(map(lambda state: state.alias, Service.get_aircons()))
  File "/config/custom_components/ds_air/ds_air_service/service.py", line 204, in get_aircons
    return Service._new_aircons+Service._aircons+Service._bathrooms
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
`

一直在初始化
Home Assistant 2022.11.1
Supervisor 2022.10.2
Operating System 9.3
前端版本： 20221102.1 - latest

**Comment by xrh0905** [comment]
与 #36 重合
