### ISSUE TITLE
开始报错了

### ISSUE THREAD

**Issue by ItownTech** [mypal/ha-dsair#38]
重新装了home assistant，通过hacs添加好dsair之后，启动报错。
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/pi/.homeassistant/custom_components/ds_air/ds_air_service/service.py", line 134, in run
    Service.poll_status()
  File "/home/pi/.homeassistant/custom_components/ds_air/ds_air_service/service.py", line 292, in poll_status
    for i in Service._new_aircons:
TypeError: 'NoneType' object is not iterable

**Comment by xrh0905** [comment]
与 #36 相似
