### ISSUE TITLE
HA 最新版本报错

### ISSUE THREAD

**Issue by yokle** [mypal/ha-dsair#57]
Logger: homeassistant.config_entries
Source: custom_components/ds_air/__init__.py:51
Integration: DS-AIR ([documentation](https://github.com/mypal/ha-dsair))
First occurred: 22:33:54 (1 occurrences)
Last logged: 22:33:54

Error setting up entry 金制空气 for ds_air
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ds_air/__init__.py", line 51, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by xrh0905** [comment]
确定是最新版本吗
这个问题在集成1.3.3就已经修复了
@yokle
