### ISSUE TITLE
添加集成失败

### ISSUE THREAD

**Issue by zcq100** [mypal/ha-dsair#60]
```
Home Assistant 2023.4.6
前端版本： 20230411.1 - latest
```
在添加集成的时候发生错误，提示：
```
无法加载配置向导: {"message":"Invalid handler specified"}
```

https://github.com/mypal/ha-dsair/blob/21c8dbd4ad0bbda90eb4bc4e8026f50c7199bcac/custom_components/ds_air/ds_air_service/ctrl_enum.py#L302

```
Logger: homeassistant.loader
Source: custom_components/ds_air/ds_air_service/ctrl_enum.py:302
Integration: DS-AIR ([documentation](https://github.com/mypal/ha-dsair))
First occurred: 22:22:41 (4 occurrences)
Last logged: 22:24:09

Unexpected exception importing platform custom_components.ds_air.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/ds_air/__init__.py", line 12, in <module>
    from .const import CONF_GW, DEFAULT_HOST, DEFAULT_PORT, DEFAULT_GW, DOMAIN
  File "/config/custom_components/ds_air/const.py", line 5, in <module>
    from .ds_air_service.ctrl_enum import EnumSensor
  File "/config/custom_components/ds_air/ds_air_service/ctrl_enum.py", line 302, in <module>
    HVACAction.DRYING, None, None, HVACAction.PREHEATING, HVACAction.DRYING]
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: PREHEATING
```

**Comment by zcq100** [comment]
早上把hass更新了，更新到7.3后，没问题了。
如果和hass版本有关，建议加上依赖说明。
```
Home Assistant 2023.7.3
前端版本： 20230705.1 - latest
```

**Comment by xrh0905** [comment]
确实是版本问题 最新的PR把`PREHEATING`这个动作加入映射表了，但目前这个动作在`2023.7.0`才加入Home Assistant.
快速解决方法是把`HVACAction.PREHEATING`改为`HVACAction.HEATING`，也就是回滚到上一个版本的行为。
