### ISSUE TITLE
求助 安装不了一直转圈

### ISSUE THREAD

**Issue by jathycn** [mypal/ha-dsair#65]
<img width="456" alt="微信图片_20230914062553" src="https://github.com/mypal/ha-dsair/assets/55263125/6c35856f-901d-4258-a41c-d54ae11b2ffc">
一直这样 求助

**Comment by Necroneco** [comment]
一般来讲是网络问题

**Comment by tomcatGu** [comment]
我的也是转圈圈。以下是日志
日志详细信息( ERROR )

Logger: homeassistant.config_entries
Source: config_entries.py:444
First occurred: 上午9:28:59 (2 occurrences)
Last logged: 上午9:29:04

Error setting up entry 金制空气 for ds_air
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ds_air/__init__.py", line 51, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'. Did you mean: 'async_unload_platforms'?

在ha2022.11里正常，在ha2024中装不了。

**Comment by Necroneco** [comment]
> 我的也是转圈圈。以下是日志 日志详细信息( ERROR )
> 
> Logger: homeassistant.config_entries Source: config_entries.py:444 First occurred: 上午9:28:59 (2 occurrences) Last logged: 上午9:29:04
> 
> Error setting up entry 金制空气 for ds_air Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup result = await component.async_setup_entry(hass, self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/ds_air/**init**.py", line 51, in async_setup_entry hass.config_entries.async_setup_platforms(entry, PLATFORMS) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'. Did you mean: 'async_unload_platforms'?
> 
> 在ha2022.11里正常，在ha2024中装不了。

检查一下集成版本，这个问题应该一年前就修了 #45

**Comment by tomcatGu** [comment]
ha版本是这样的,我从ds1.3.2试到1.3.4
Core
2024.2.2
Supervisor
2024.02.0
Operating System
11.5
前端
20240207.1

**Comment by xrh0905** [comment]
> ha版本是这样的,我从ds1.3.2试到1.3.4 Core 2024.2.2 Supervisor 2024.02.0 Operating System 11.5 前端 20240207.1

试试直接走test分支？
重新确认下集成版本，我怀疑你下的还是旧版。

**Comment by tomcatGu** [comment]
我用wget 下载的。顺便问下，我装的HACS极速版1.33.0.3，自定义库下载不了ds-air,选完版本后，点下载也是一直转圈。

**Comment by Necroneco** [comment]
> 我用wget 下载的。顺便问下，我装的HACS极速版1.33.0.3，自定义库下载不了ds-air,选完版本后，点下载也是一直转圈。

我起了一个新的HA实例，用HACS极速版确实能重现转圈，看日志似乎在解压zip的步骤出错了，但没找到问题原因。
然后我换原版HACS没有问题。

**Comment by tomcatGu** [comment]
如何切换到原版？

**Comment by Necroneco** [comment]
> 如何切换到原版？


按原版的卸载流程 https://hacs.xyz/docs/setup/remove 就是：
- 先在 设备与服务 里面把 HACS 删掉
- 然后重启HA两次
- 然后把 /custom_componets/hacs/ 这个文件夹删掉
- 再重启HA一次
- 然后再重新安装原版HACS https://hacs.xyz/docs/setup/download

不过嘛，我觉得你这次就手动装一下这个集成算了。（感觉不太应该是极速版的问题，但我也不知道具体问题在哪）

**Comment by Necroneco** [comment]
> 我手动下载安装1.3.4版,一直显示正在初始化,我的网关是D611

先看看IP有没有写错

也可以把日志打开看看

```yaml
logger:
  default: warning
  logs:
    custom_components.ds_air: debug
```

我新开的实例是可以正常添加的, 我也是D611
