### ISSUE TITLE
请教一下，连不上8008端口是什么情况？

### ISSUE THREAD

**Issue by jinmdwow** [mypal/ha-dsair#66]
之前是好的，有一天重启了一下大金的网关，就再也连不上了，下面debug日志，请大神指点一下这是什么情况？
（网关的IP是对的，能PING通）

2023-10-27 12:08:43.431 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: ds_air
2023-10-27 12:09:43.533 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: ds_air
2023-10-27 12:10:43.633 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: ds_air
2023-10-27 12:11:43.738 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: ds_air
2023-10-27 12:12:41.373 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 金制空气 for ds_air
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ds_air/__init__.py", line 49, in async_setup_entry
    await hass.async_add_executor_job(Service.init, host, port, scan_interval)
asyncio.exceptions.CancelledError: Global task timeout
2023-10-27 12:12:41.395 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for stage 2 - moving forward
2023-10-27 13:28:33.393 DEBUG (SyncWorker_2) [custom_components.ds_air.ds_air_service.service] connected error192.168.124.13:8008
2023-10-27 13:28:33.393 DEBUG (SyncWorker_2) [custom_components.ds_air.ds_air_service.service] [Errno 111] Connection refused
2023-10-27 13:28:35.151 DEBUG (SyncWorker_7) [custom_components.ds_air.ds_air_service.service] connected error192.168.124.13:8008
2023-10-27 13:28:35.152 DEBUG (SyncWorker_7) [custom_components.ds_air.ds_air_service.service] [Errno 111] Connection refused
2023-10-27 13:28:36.433 DEBUG (SyncWorker_2) [custom_components.ds_air.ds_air_service.service] connected error192.168.124.13:8008
2023-10-27 13:28:36.433 DEBUG (SyncWorker_2) [custom_components.ds_air.ds_air_service.service] [Errno 111] Connection refused

**Comment by jinmdwow** [comment]
找到错了，没问题了，是IP写错了
