### ISSUE TITLE
Uncaught thread exception

### ISSUE THREAD

**Issue by kamingchan** [mypal/ha-dsair#7]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/config/custom_components/ds_air/ds_air_service/service.py", line 83, in run
    res = self._sock.recv()
  File "/config/custom_components/ds_air/ds_air_service/service.py", line 69, in recv
    r, b = decoder(data)
  File "/config/custom_components/ds_air/ds_air_service/decoder.py", line 25, in decoder
    return result_factory(struct.unpack('<BHBBBBIBIBH' + str(length - 16) + 'sB', b[:length + 4])), b[length + 4:]
  File "/config/custom_components/ds_air/ds_air_service/decoder.py", line 88, in result_factory
    result.load_bytes(subbody)
  File "/config/custom_components/ds_air/ds_air_service/decoder.py", line 180, in load_bytes
    self._sensor_type = d.read1()
  File "/config/custom_components/ds_air/ds_air_service/decoder.py", line 100, in read1
    s = struct.unpack('<B', self._b[pos:pos + 1])[0]
struct.error: unpack requires a buffer of 1 bytes
```

code version: master
device version: DTA117C611

**Comment by mypal** [comment]
1.2.0版本已支持DTA117C611

**Comment by kamingchan** [comment]
![image](https://user-images.githubusercontent.com/9930758/125951585-009d8066-2320-4f2d-88d3-00574be33926.png)

似乎无法识别到设备，但用 https://github.com/hicaoc/ha-dsair 这个fork的版本是可以看到室内机的。

**Comment by mypal** [comment]
> ![image](https://user-images.githubusercontent.com/9930758/125951585-009d8066-2320-4f2d-88d3-00574be33926.png)
> 
> 似乎无法识别到设备，但用 https://github.com/hicaoc/ha-dsair 这个fork的版本是可以看到室内机的。

大金分新老空调，估计你的是老空调，正在改代码。晚一点可以试试新版本

**Comment by mypal** [comment]
试一下1.2.3版本吧

**Comment by kamingchan** [comment]
我这边有两台DTA117C611，更新了最新的1.2.3，其中一台下面只有空调，能成功识别、控制。

另外一台下面除了空调（型号不同）还有两个传感器，配置的时候报错。

```

2021-07-25 16:10:54 ERROR (Thread-11) [root] Uncaught thread exception,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner,
    self.run(),
  File "/config/custom_components/ds_air/ds_air_service/service.py", line 98, in run,
    res, data = self._sock.recv(),
  File "/config/custom_components/ds_air/ds_air_service/service.py", line 80, in recv,
    r, b = decoder(data),
  File "/config/custom_components/ds_air/ds_air_service/decoder.py", line 24, in decoder,
    return result_factory(struct.unpack('<BHBBBBIBIBH' + str(length - 16) + 'sB', b[:length + 4])), b[length + 4:],
  File "/config/custom_components/ds_air/ds_air_service/decoder.py", line 85, in result_factory,
    result.load_bytes(subbody),
  File "/config/custom_components/ds_air/ds_air_service/decoder.py", line 177, in load_bytes,
    self._sensor_type = d.read1(),
  File "/config/custom_components/ds_air/ds_air_service/decoder.py", line 97, in read1,
    s = struct.unpack('<B', self._b[pos:pos + 1])[0],
struct.error: unpack requires a buffer of 1 bytes,
```

**Comment by kamingchan** [comment]
看Traceback应该是Sensor2InfoResult的解码出错了，目前在使用的型号是BRY88AA151K
